
export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAIL = 'PAYMENT_FAIL';

export const PAYMENT_CONFIRM_REQUEST = 'PAYMENT_CONFIRM_REQUEST';
export const PAYMENT_CONFIRM_SUCCESS = 'PAYMENT_CONFIRM_SUCCESS';
export const PAYMENT_CONFIRM_FAIL = 'PAYMENT_CONFIRM_FAIL';

export const PAYMENT_RETRY_REQUEST = 'PAYMENT_RETRY_REQUEST';
export const PAYMENT_RETRY_SUCCESS = 'PAYMENT_RETRY_SUCCESS';
export const PAYMENT_RETRY_FAIL = 'PAYMENT_RETRY_FAIL';

export const PAYMENT_CANCEL_REQUEST = 'PAYMENT_CANCEL_REQUEST';
export const PAYMENT_CANCEL_SUCCESS = 'PAYMENT_CANCEL_SUCCESS';
export const PAYMENT_CANCEL_FAIL = 'PAYMENT_CANCEL_FAIL';
