export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';

export const FETCH_SERVICE_BY_ID_REQUEST = 'FETCH_SERVICE_BY_ID_REQUEST';
export const FETCH_SERVICE_BY_ID_SUCCESS = 'FETCH_SERVICE_BY_ID_SUCCESS';
export const FETCH_SERVICE_BY_ID_FAILURE = 'FETCH_SERVICE_BY_ID_FAILURE';
